# Generated by Django 5.0.2 on 2024-03-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_alter_like_is_dislike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="is_dislike",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
