# Generated by Django 5.0.2 on 2024-03-02 12:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_alter_like_is_dislike"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="post",
            new_name="publication",
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("publication", "user")},
        ),
    ]
